#!/usr/bin/env python

# This script contains the standard supervised learning algorithm. It 
# repeatedly collects episodes of expert demonstrations using the expert
# policy with some additive noise and trains the neural network policy
# with the collected dataset at the end. It also contains a separate 
# execution feature that tests the current model in getting the robot from 
# point A to point B.


import rospy
import actionlib
from move_base_msgs.msg import MoveBaseAction, MoveBaseGoal
from geometry_msgs.msg import Twist, Pose, PoseWithCovarianceStamped
from sensor_msgs.msg import LaserScan, Image
from nav_msgs.msg import Odometry
from std_msgs.msg import String, Bool
from cs6244.srv import Mode, ModeResponse

import numpy as np
import json

import argparse
import os
import random

from model_il import ImitationNet
import model_il
import torch


# global data msgs
expert_cmd = None
laser = None 
pos = None 
image = None

# constants for the mode
IDLE = 0
COLLECT = 1
TRAIN = 2
EXECUTE = 3

currmode = None

# constant for trajectory saving file name
num_traj = 0



# Topic Callbacks
def expertCmdCallback(vel):
	global expert_cmd
	expert_cmd = vel

def laserCallback(scan):
	global laser
	laser = scan

def amclCallback(amcl):
	global pos
	pos = amcl

def handleModeChange(m):
	global currmode, pos, laser

	reqmode = int(m.reqmode)
	if reqmode == COLLECT:
		rospy.loginfo(rospy.get_caller_id() + ": COLLECT MODE")
	elif reqmode == TRAIN:
		rospy.loginfo(rospy.get_caller_id() + ": TRAIN MODE")
	elif reqmode == EXECUTE:
		rospy.loginfo(rospy.get_caller_id() + ": EXECUTE MODE")
	elif reqmode == CLEARDATA:
		rospy.loginfo(rospy.get_caller_id() + ": CLEARDATA MODE")
	elif reqmode == IDLE:
		pos = laser = image = command = None 
		rospy.loginfo(rospy.get_caller_id() + ": IDLE MODE")
	else:
		reqmode = currmode 
		
	currmode = reqmode
	return ModeResponse(currmode)

def recordData2File(D):
	"""
	Process the latest trajectory data by removing all points that the turtlebot is not
	moving and dump the trajectory into a json file.
	"""
	global num_traj

	# Write to the correct file name
	file_name = args.data_dir + "trajectory_" + str(num_traj) + '.json'
	while os.path.exists(file_name):
		num_traj += 1
		file_name = args.data_dir + "trajectory_" + str(num_traj) + '.json'

	# Write to json file
	if len(D["robot_vel"]) > 0:
		with open(file_name, 'w') as fout:
			json.dump(D, fout)
		num_traj += 1

def resetRobotState():
	pub_reset.publish(True)
	rospy.sleep(0.1)
	pub_reset.publish(True)		# Repeat to make sure reset at the right pose


def collect(D):
	global currmode, expert_cmd, pos, laser

	# Noise variable
	noise_count = 0
	noise = 0.0

	# Start the expert planning first and let it run in the background
	goal = MoveBaseGoal()
	goal.target_pose.header.frame_id = "map"
	goal.target_pose.header.stamp = rospy.Time.now()
	goal.target_pose.pose.position.x = 6.0
	goal.target_pose.pose.position.y = -1.0
	goal.target_pose.pose.orientation.z = 0.7071
	goal.target_pose.pose.orientation.w = -0.7071
	client.send_goal(goal)
	print('starting expert planning')

	robot_cmd = Twist()

	# Control robot until robot reached goal state
	while True:
		if expert_cmd is not None:
		# Check if goal is reached
			if (abs(pos.pose.pose.position.x - 6.0) < 0.5 and \
				abs(pos.pose.pose.position.y + 1.0) < 0.1) or \
				(expert_cmd.linear.x == 0.0 and expert_cmd.angular.z == 0.0):
				print('test', pos.pose.pose.position.x)
				# Stop the robot
				robot_cmd = Twist()
				robot_cmd.linear.x, robot_cmd.angular.z = 0.0, 0.0
				pub_cmd.publish(robot_cmd)
				# Stop the expert policy path planning
				print('Stopping expert planning.')
				client.cancel_goal()
				# Reset robot to start state
				print("Demonstration complete. Resetting robot to start")
				resetRobotState()
				# Change mode back to IDLE
				print('Collection done.')
				currmode = IDLE
				break

		
			# Always use expert policy
			print('expert {:10.6f}, {:10.6f}'.format(expert_cmd.linear.x, expert_cmd.angular.z))
			robot_cmd.linear.x = expert_cmd.linear.x
			if noise_count % 100 == 0:
				if np.random.randint(2):
					noise = np.random.uniform(low=0.1, high=0.2)
				else:
					noise = np.random.uniform(low=-0.2, high=-0.1)
			robot_cmd.angular.z = expert_cmd.angular.z + noise
			pub_cmd.publish(robot_cmd)

			# Update D
			robot_pos = [pos.pose.pose.position.x, pos.pose.pose.position.y,
						pos.pose.pose.position.z, pos.pose.pose.orientation.x,
						pos.pose.pose.orientation.y, pos.pose.pose.orientation.z, 
						pos.pose.pose.orientation.w]
			robot_vel = [expert_cmd.linear.x, expert_cmd.angular.z]

			D["robot_pos"] += [robot_pos]
			D["laser_scan"] += [laser.ranges]
			D["robot_vel"] += [robot_vel]

			noise_count += 1

		# Sleep for the remaining time
		rate.sleep()

	return D


def train():
	global currmode, model

	# Load model again
	if os.path.exists(args.model_dir + 'model.pt'):
		model.load(args.model_dir + 'model.pt')
	model = model.to(args.device)

	# train neural network
	model = model_il.train(model, mode='supervised')
	model.eval()

	# Reset robot to start state
	print("Training round complete. Resetting robot to start")
	resetRobotState()

	# Done training, return to idle
	print("Returning to Idle mode.")
	currmode=IDLE

	return model

def execute():
	global currmode, model

	# Load model again
	if os.path.exists(args.model_dir + 'model.pt'):
		model.load(args.model_dir + 'model.pt')
	model = model.to(args.device)
	model.eval()

	# Keep executing until goal is reached
	while True:
		# Run network policy to get control command 
		odom_input = np.array([[pos.pose.pose.position.x, 
								pos.pose.pose.position.y,
								pos.pose.pose.position.z,
								pos.pose.pose.orientation.x, 
								pos.pose.pose.orientation.y, 
								pos.pose.pose.orientation.z, 
								pos.pose.pose.orientation.w]])
		laser_scan = np.array([laser.ranges])

		vel = model_il.test(model, odom_input, laser_scan)
		robot_cmd = Twist()
		robot_cmd.linear.x = vel[0,0]
		robot_cmd.angular.z = vel[0,1]
		pub_cmd.publish(robot_cmd)

		if abs(pos.pose.pose.position.x - 6.0) < 1.0 and \
				abs(pos.pose.pose.position.y + 1.0) < 0.3:
			# Stop the robot
			robot_cmd.linear.x, robot_cmd.angular.z = 0.0, 0.0
			pub_cmd.publish(robot_cmd)
			# Reset robot to start state
			print("Goal is reached. Resetting robot to start")
			resetRobotState()
			# Change mode back to IDLE
			print('Testing round successful. Going back to IDLE mode.')
			currmode = IDLE
			break

		# Sleep for the remaining time
		rate.sleep()

	#done training, return to idle
	currmode=IDLE

def clearDataset():
	# Initialize Dataset D
	D = {'robot_pos': [], 'laser_scan': [], 'robot_vel':[]}
	return D



if __name__=='__main__':
	parser = argparse.ArgumentParser(description="parse args")
	parser.add_argument('--model_dir', type=str, 
						default=os.path.expanduser('~')+'/catkin_ws/src/cs6244/models/supervised/')
	parser.add_argument('--data_dir', type=str, 
						default=os.path.expanduser('~')+'/catkin_ws/src/cs6244/data/supervised/')
	parser.add_argument('--device', type=str, default='cpu')
	args = parser.parse_args()

	# configure cuda
	if torch.cuda.is_available():
	    print('cuda is available')
	    args.device = torch.device('cuda')
	else:
	    print('cuda is not available')
	    args.device = "cpu"

	rospy.init_node('learner', anonymous=True)

	# service handler
	modeservice = rospy.Service('mode_change', Mode, handleModeChange)

	# add callbacks
	rospy.Subscriber("scan", LaserScan, laserCallback)
	rospy.Subscriber("amcl_pose", PoseWithCovarianceStamped, amclCallback)
	rospy.Subscriber("/cmd_vel_temp", Twist, expertCmdCallback)

	# add ROS publishers
	pub_reset = rospy.Publisher("reset_robot_pos", Bool, queue_size=10)
	pub_cmd = rospy.Publisher("/cmd_vel", Twist, queue_size=10)

	# Initialize move_base SimpleActionClient
	client = actionlib.SimpleActionClient('move_base',MoveBaseAction)
	client.wait_for_server()

	# Initialize rate for controlling robot and updating observations
	rate = rospy.Rate(20) #Hz

	# Initialize model
	model = ImitationNet(control_dim=2, device=args.device)

	# Initialize dataset and sliding window for data recording
	D = clearDataset()

	# main loop
	while not rospy.is_shutdown():
		if currmode == COLLECT:
			D = collect(D)
		elif currmode == TRAIN:
			train()
		elif currmode == EXECUTE:
			execute()
		else:
			# write data to json file and reset D
			if len(D['robot_pos']) > 0:
				recordData2File(D)
				D = clearDataset()
				print('Going back to collect')
				expert_cmd = None
				currmode = COLLECT
			D = clearDataset()

		# sleep for the remaining time
		rate.sleep()