#!/usr/bin/env python

# This script resets the robot's position to A.
# You may wish to add some noise to the robot position.


import rospy
from geometry_msgs.msg import Twist, Pose 
from gazebo_msgs.srv import SetModelState
from gazebo_msgs.msg import ModelState 


def resetRobotPosition():
	rospy.init_node('reset_robot_pos')

	state_msg = ModelState()
	state_msg.model_name = 'turtlebot3'
	state_msg.pose.position.x = -6.503
	state_msg.pose.position.y = -2.422
	state_msg.pose.position.z = 0.00
	state_msg.pose.orientation.x = 0
	state_msg.pose.orientation.y = 0
	state_msg.pose.orientation.z = -0.77
	state_msg.pose.orientation.w = -0.63

	state_msg.twist.linear.x = 0.0
	state_msg.twist.linear.y = 0.0
	state_msg.twist.linear.z = 0.0
	state_msg.twist.angular.x = 0.0
	state_msg.twist.angular.y = 0.0
	state_msg.twist.angular.z = 0.0

	rospy.wait_for_service('/gazebo/set_model_state')
	try:
		set_state = rospy.ServiceProxy('/gazebo/set_model_state', SetModelState)
		resp = set_state( state_msg )

	except:
		print("Service call failed: %s" % e)


if __name__=='__main__':
	resetRobotPosition()



# position: 
#       x: -6.503128366844999
#       y: -2.4221654755161817
#       z: -0.0010021019490881675
#     orientation: 
#       x: 0.0029722193889993587
#       y: -0.0024604578835837475
#       z: -0.7690043208045467
#       w: -0.6392319349366429
